"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_mauve)\
$os\
$username\
[](bg:color_pink fg:color_mauve)\
$directory\
[](fg:color_pink bg:color_peach)\
$git_branch\
$git_status\
[](fg:color_peach bg:color_green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_green bg:color_sapphire)\
$docker_context\
[](fg:color_sapphire bg:color_surface0)\
$time\
[ ](fg:color_surface0)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_fg0 = '#cdd6f4'
color_surface0 = '#313244'
color_surface1 = '#45475a'
color_sapphire = '#74c7ec'
color_teal = '#94e2d5'
color_green = '#a6e3a1'
color_peach = '#fab387'
color_mauve = '#cba6f7'
color_red = '#f38ba8'
color_yellow = '#f9e2af'
color_pink = '#f5c2e7'

[os]
disabled = false
style = "bg:color_mauve fg:color_surface0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_mauve fg:color_surface0"
style_root = "bg:color_mauve fg:color_surface0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_surface0 bg:color_pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projets" = "󰲋 "
"dev" = "󰲋 "

[git_branch]
symbol = "󰘬"
style = "bg:color_peach"
format = '[[ $symbol $branch ](fg:color_surface0 bg:color_peach)]($style)'

[git_status]
style = "bg:color_peach"
format = '[[($all_status$ahead_behind )](fg:color_surface0 bg:color_peach)]($style)'

[nodejs]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[c]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[rust]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[golang]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[php]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[java]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[kotlin]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[haskell]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[python]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_green)]($style)'

[docker_context]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $context) ](fg:color_surface0 bg:color_sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_surface0"
format = '[[  $time ](fg:color_fg0 bg:color_surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❯](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❯](bold fg:color_mauve)'
vimcmd_replace_symbol = '[❯](bold fg:color_mauve)'
vimcmd_visual_symbol = '[❯](bold fg:color_yellow)'
